name: C++ CI/CD

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build the application
      run: g++ helloworld.cpp -o HelloWorld

    - name: Run the application
      run: ./HelloWorld

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: setup-zip
          path: dist
